#!/bin/bash
set -euxo pipefail

PROGRAM_NAME="$(basename $0)"
VERSION=0.1
CONFIGFILE=$(:)

function usage {
    cat << EOF
Usage: $0 [OPTIONS] [PKGBUILD] ...

This script will build a specific AUR package in an Arch Linux container 
using a clean chroot while taking care of all the dependecies. If a PKGBUILD
is found in the current working directory, the script will use that, otherwise
you have to pass it as argument to the script.

WARNING:
Please note that it assumes you have already checked every package's PKGBUILD.

OPTIONS:
    -h, --help          display this help and exit
    -v, --version       output version information and exit
EOF
}

function print_dockerfile {
    cat << EOF
FROM archlinux:latest

RUN pacman -Syu --noconfirm --noprogressbar ${pkg_list[@]}

RUN reflector --protocol https --latest 5 --save /etc/pacman.d/mirrorlist
RUN sed -i '/MAKEFLAGS/c\MAKEFLAGS=\"-j\"$(nproc --all)"\"' /etc/makepkg.conf
RUN echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/71-wheel

COPY $build_script /usr/bin/build

RUN useradd -m -G wheel -s /bin/bash  $user \
    && yes $pkg | passwd $user \
    && mkdir -p /home/$user/builds \
    && chown -R $user /home/$user/builds

COPY $pkgbuild /home/$user/builds/$(get_pkgname)

USER $user

# ENTRYPOINT  ["/usr/bin/build"]

EOF
}

function initialize {
    # download AUR package database
    if [ -e "$CACHEDIR/packages" ]; then
        rm "$CACHEDIR/packages"
    fi

    wget -q -P "$CACHEDIR" https://aur.archlinux.org/packages.gz
    gzip -q -d -c < "$CACHEDIR/packages.gz"  > "$CACHEDIR"
    AURDB="$CACHEDIR/packages"
}

function get_pkgname {
    grep "pkgname" PKGBUILD | head -n1 | cut -d"=" -f2
}

function get_pkgver {
    grep "pkgver" PKGBUILD | head -n1 | cut -d"=" -f2
}

function get_pkgrel {
    grep "pkgrel" PKGBUILD | head -n1 | cut -d"=" -f2
}

function get_arch {
    grep "arch" PKGBUILD | head -n1 | cut -d"=" -f2
}

function get_user {
    last | head -n1 | cut -d" " -f1 | xargs
}

function remove_whitespaces {
    # for (( i=0; i<${#temp[@]}; i++ )) ; do echo -e "before=\"${temp[$i]}\"\t" && temp[$i]=$(echo "${temp[$i]}" | xargs) && echo -e "after=\"${temp[$i]}\"\n" ; done
    local -n temp=$1
    for (( i=0; i<${#temp[@]}; i++ )) ; do 
        temp[$i]=$(echo "${temp[$i]}" | xargs)
    done
}


### START ###
source "$CONFIGFILE"
pkgbuild="$(find "$(pwd)" -maxdepth 1 -name "PKGBUILD")"
pkg="$(get_pkgname)-$(get_pkgver)-$(get_pkgrel)"
user="$pkg"
pkg_list=(
    'base-devel'
    'reflector'
    'devtools'
    'namcap'
)

# container manager check
# thanks https://github.com/89luca89/distrobox
if command -v podman > /dev/null; then
    container_manager="podman"
elif command -v docker > /dev/null; then
    container_manager="docker"
else
    echo "no container manager found, please install one (podman is recommended).\n" 1>&2
    exit 1
fi

# parse command line arguments
while [[ "$1" ]]; do
    case $1 in
        "-h" | "--help") 
            usage
            exit 0
            ;;
        "-v" | "--version")
            echo "$0 $version"
            exit 0
            ;;
        ?)
            echo "Invalid Option: -${OPTARG}" 1>&2
            usage
            exit 1
            ;;
        :)
            echo "Option -"${OPTARG}" requires an argument." 1>&2
            usage
            exit 1
            ;;
    esac

    shift
done

while [[ "$1" ]]; do
    if [[ "$(basename "$1")" == "PKGBUILD" ]]; then
        pkgbuild="$1"
    fi

    shift
done


# do shit
print_dockerfile > "$dockerfile"

"$container_manager" build "$(pwd)"

"$container_manager" run -it --rm 



exit 0