#!/bin/bash
set -e

PROGRAM_NAME="aht"
VERSION="$(git tag | head -n1)"

# check dependencies
dependencies=(
    'wget'
    'gzip'
)

printf "Checking dependencies...\t"
for p in "${dependencies[@]}"; do
    if ! command -v "$p" > /dev/null; then
        echo "$p not found, please install it.\n" 1>&2
        exit 1
    fi    
done
printf "Done.\n"

# data
if [ -z ${XDG_DATA_HOME+x} ]; then
    DATADIR="$HOME/.local/share/$PROGRAM_NAME"
else
    DATADIR="$XDG_DATA_HOME/$PROGRAM_NAME"
fi
mkdir -p "$DATADIR"

# binaries directory
BINDIR="$HOME/.local/bin"

if [ ! -d "$BINDIR" ]; then
    mkdir -p "$BINDIR"
fi

if [[ ! ":$PATH:" == *":$BINDIR:"* ]]; then
    echo "Add $BINDIR to \$PATH to correctly use $PROGRAM_NAME" 1>&2
    exit 1
fi

# cache
if [ -z ${XDG_CACHE_HOME+x} ]; then    
    CACHEDIR="$HOME/.cache/$PROGRAM_NAME"
else
    CACHEDIR="$XDG_CACHE_HOME/$PROGRAM_NAME"
fi
mkdir -p "$CACHEDIR"

# init AUR packages database
printf "Downloading AUR packages database...\t"
AURDB="$CACHEDIR/packages"
wget -q -P "$CACHEDIR" https://aur.archlinux.org/packages.gz
gzip -q -d -c < "$CACHEDIR/packages.gz"  > "$AURDB"
rm "$CACHEDIR/packages.gz"
printf "Done.\n"

# create config file
if [ -z ${XDG_CONFIG_HOME+x} ]; then
    CONFIGDIR="$HOME/.config/$PROGRAM_NAME"
else
    CONFIGDIR="$XDG_CONFIG_HOME/$PROGRAM_NAME"
fi
mkdir -p "$CONFIGDIR"

CONFIGFILE="$CONFIGDIR/${PROGRAM_NAME}rc"
if [ ! -e "$CONFIGFILE" ]; then
    echo -e "# $PROGRAM_NAME configuration file\n" > "$CONFIGFILE"
fi

BUILD_SCRIPT="$DATADIR/${PROGRAM_NAME}-build"

# install
install -Dm755 "$PROGRAM_NAME" -t $BINDIR
install -Dm644 "${PROGRAM_NAME}-build" -t $DATADIR

sed -i "/^CONFIGFILE/c\CONFIGFILE=$CONFIGFILE" "$BINDIR/$PROGRAM_NAME"
sed -i "/^VERSION/c\VERSION=$VERSION" "$BINDIR/$PROGRAM_NAME"
sed -i "/^PROGRAM_NAME/c\PROGRAM_NAME=$PROGRAM_NAME" "$BINDIR/$PROGRAM_NAME"

cat >> "$CONFIGFILE" << EOF
DATADIR="$DATADIR"
BINDIR="$BINDIR"
CACHEDIR="$CACHEDIR"
CONFIGDIR="$CONFIGDIR"
AURDB="$AURDB"
BUILD_SCRIPT="$BUILD_SCRIPT"
EOF

echo "$PROGRAM_NAME successfully installed, make sure $BINDIR is part of your \$PATH."

exit 0